"""Generate a C++ header with predefined subtitles encoded as Big5 byte arrays.

Avoids needing iconv at runtime (mingw doesn't ship libiconv by default).
"""
SUBTITLES = [
    ("nwc",          "天際寒星 - 繁體中文化版"),
    ("commander",    "司令官波克 - 拯救地球任務"),
    ("press_any",    "按任意鍵繼續"),
    ("coming_soon",  "敬請期待 中文化測試版本"),
    ("by_community", "本譯版由社群製作"),
    ("nwc_logo",     "新世界電腦 - 一九九二年作"),
]

OUT = "/mnt/d/03_tools/poc/sdl2_spike/src/Subtitles.h"

def to_big5(s):
    return s.encode('cp950', errors='replace')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write("""/* Subtitles.h — auto-generated by gen_subtitles.py.
 * Pre-encoded Big5 (cp950) bytes for demo subtitles. */
#pragma once
#include <cstdint>
#include <span>
#include <string>

namespace pe {

struct Subtitle {
    const char     *id;
    const char     *utf8;       // for logging only
    const uint8_t  *big5_bytes;
    size_t          big5_len;
};

""")
    for sid, txt in SUBTITLES:
        big5 = to_big5(txt)
        arr = ', '.join(f'0x{b:02X}' for b in big5)
        f.write(f'static const uint8_t kSubtitle_{sid}_bytes[] = {{ {arr} }};\n')
    f.write("\n")
    f.write("static const Subtitle kSubtitles[] = {\n")
    for sid, txt in SUBTITLES:
        big5 = to_big5(txt)
        f.write(f'    {{ "{sid}", "{txt}", kSubtitle_{sid}_bytes, sizeof(kSubtitle_{sid}_bytes) }},\n')
    f.write("};\n")
    f.write(f"static const size_t kSubtitlesCount = {len(SUBTITLES)};\n")
    f.write("\n} // namespace pe\n")

print(f"wrote {OUT}")
for sid, txt in SUBTITLES:
    big5 = to_big5(txt)
    print(f"  [{sid}] '{txt}' -> {len(big5)} bytes")
